spring:
  profiles:
    active: local, sensitive
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 1000
        use_sql_comments: true # QueryDsl 실행 쿼리를 jpql로도 보고 싶을 때
  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나당 최대 크기
      max-request-size: 100MB # 요청당 최대 크기

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

#상품 이미지 업로드 경로
itemImgLocation: C:\shop\item
#리소스 업로드 경로
uploadPath: file:\\\C:\shop\